### ISSUE TITLE
JAVA 8 inkompatipel

### ISSUE THREAD

**Issue by RobertPaasche** [anotheria/moskito-central#21]
Das verwendete maven Plugin apt-maven-plugin ist nicht mit JAVA >= 8 kompatibel.

**Comment by dvayanu** [comment]
So? ;-)

**Comment by RobertPaasche** [comment]
#22 Pull request wurde erstellt.

**Comment by dvayanu** [comment]
Danke/Thanks. Roman will review the pull request shortly!

**Comment by dvayanu** [comment]
fixed it with https://github.com/anotheria/moskito-central/pull/23
