### ISSUE TITLE
java.io.EOFException: No content to map to Object due to end of input

### ISSUE THREAD

**Issue by strang3quark** [anotheria/moskito-central#28]
When integrating with my Application I'm getting this error on the client: 

ERROR - RESTConnector.sendData() failed: java.net.SocketException: Connection reset

After looking at the Central logs I found this on tomcat stderr.

https://pastebin.com/QKyKjSQ9

This is what my application is sending:

https://pastebin.com/Uh4VJXGK

**Comment by dvayanu** [comment]
added 'sent' data to the ticket directly
{"stats":{"entries":[{"key":"session-refIds-7","value":{}}]},"snshmd":{"producerId":"session-refIds-7","componentName":"app","hostName":"MAX-BJ","intervalName":"1m","creationTimestamp":1530175285476,"arrivalTimestamp":1530175285639,"category":"storage","subsystem":"default","statClassName":"net.anotheria.moskito.core.util.storage.StorageStats"}}

**Comment by dvayanu** [comment]
@strang3quark we've tried to reproduce with your data, but it works ok, for our application. Have you tried to send the request from postman? Did it success?
Alternatively, can you try to send the same data from a shell, a) on you central server itself, b) from the same machine your moskito-client is located? This would help to illuminate connectivity issues between the machines.
Also, what moskito version are you using?

**Comment by strang3quark** [comment]
I just remembered we left this open. The problem was on the company's network. Sorry for wasting your time.
